### ISSUE TITLE
Automated generation of SDL API documentation for both SDL 2 and SDL 3?

### ISSUE THREAD

**Issue by blaisemccourtney** [libsdl-org/sdlweb#18]
The sdlwiki might have its SDL API documentation manually created and updated. There are some advantages and some drawbacks to this.

This issue is made to ask and discuss whether this would be a welcome addition to the website: Automatically generated API documentation for both SDL 2 and SDL 3 as part of the website.

There's a bit of a start of a discussion in the SDL Enthusiasts Discord.

**Comment by slouken** [comment]
The wiki is bridged to the headers by an automated process that takes care of the functions. Hints and other meta documentation is all handled manually and can definitely use some love.

**Comment by blaisemccourtney** [comment]
Thank you for mentioning https://github.com/libsdl-org/SDL/blob/main/build-scripts/wikiheaders.pl on Discord. I would have an easier time working with that script if it was refactored, 1700+ lines of Perl with heavy regex usage and long code blocks is a bit daunting.

**Comment by blaisemccourtney** [comment]
I made a new issue at https://github.com/libsdl-org/SDL/issues/9236, so that other developers can keep track of the issues that I have found, and maybe handle them.
