### ISSUE TITLE
Stylesheets vs iPhone...

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdlweb#9]
This was emailed to me, so I'm posting it here so it can get looked at sometime.

We probably _should_ have this flow vertically instead of horizontally if we're on a mobile device (or maybe just in general, idk).

---

> Hey there, I have to update the Stylesheets some time. They are deprecated. See screenshot. This is how it looks on my iPhone. 
>
> ![image](https://user-images.githubusercontent.com/673562/189725809-b8b7e4ff-8370-44b8-8429-42b09e57306d.png)

**Comment by slouken** [comment]
Fixed in https://github.com/libsdl-org/sdlweb/commit/437d4a3276dfee4aa266a3e2fa18df0b8d2fe031
